project:
  type: book
  output-dir: docs

book:
  title: "生物信息大百科"
 # author: "Wang Tong"
 # date: "2023/8/13"
  cover-image: cover.jpg
  cover-image-alt: "Hello, World"
  language: zh
  favicon: favicon.png
  site-url: https://gene.wiki
  repo-url: https://github.com/wangtong/mybook
  repo-branch: main
  repo-actions: [edit, issue]
  reader-mode: false

  sidebar: 
    search: true
    style: floating
    background: lightblue
    border: false
  
  page-footer:
    left: |
      基因学苑生物信息百科全书
      
    right: |
      这本书使用 <a href="https://quarto.org/">Quarto</a>编写.
  
  chapters:
    - index.qmd
    
    - preface.qmd
    - intro.qmd
#    - summary.qmd
#    - references.qmd

#    - introduction.Rmd

    - part: 生物信息
#      chapters: 
      

    - part: Linux
#      chapters: 
#      - whole-geme.qmd


    - part: 生物软件安装
#      chapters: 
#      - whole-geme.qmd


    - part: R语言
      chapters: 
      - rbase-1.qmd
      - rbase-2.qmd


    - part: 测序原理
#      chapters: 
#      - whole-geme.qmd

    - part: 生物信息分析平台搭建
#      chapters: 
#      - whole-geme.qmd


bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - r4ds.scss
    code-link: true
    
    author-meta: "王通"
    include-in-header: "plausible.html"


editor: visual

